import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";

const C=window.MPH_CONFIG||{};
const LS_KEY='mph-cloud-cache-v1', KEY_STORE='mph-publishable-key';
const $=id=>document.getElementById(id);
let supabase,user,rows=[],currentId=null,saveTimer=null,modalKind='',editProject=false,channel=null;
const emptyData=()=>({goal:'',type:'일반 프로젝트',phases:[{id:crypto.randomUUID(),name:'기획',progress:0},{id:crypto.randomUUID(),name:'진행',progress:0},{id:crypto.randomUUID(),name:'검토',progress:0},{id:crypto.randomUUID(),name:'완료',progress:0}],tasks:[],documents:[],roadmap:[],logs:[],ideas:[],bugs:[],releases:[]});
const seedData=()=>({goal:'누구나 쉽고 편안하게 사용할 수 있는 AI 여행 동반자를 만든다.',type:'제품 개발',phases:[{id:'p1',name:'제품 기획',progress:100},{id:'p2',name:'UI/UX 설계',progress:35},{id:'p3',name:'개발',progress:0},{id:'p4',name:'테스트',progress:0},{id:'p5',name:'출시',progress:0}],tasks:[{id:'t1',title:'Product Charter와 PRD 확정',detail:'기획',done:true},{id:'t2',title:'Sitemap과 User Flow 설계',detail:'UI/UX',done:false}],documents:[{id:'d1',title:'Product Charter',detail:'제품 비전·철학·원칙',status:'완료'},{id:'d2',title:'PRD v1.0',detail:'핵심 요구사항과 MVP',status:'진행 중'}],roadmap:[{id:'r1',title:'v1.0 핵심 제품',detail:'프로젝트 관리 기반 완성',date:'1단계'}],logs:[{id:'l1',title:'제품 기획 확정',detail:'Product Charter와 PRD 초안을 정리했습니다.',date:new Date().toLocaleDateString('ko-KR')}],ideas:[],bugs:[],releases:[{id:'v1',title:'Planning v1.0',detail:'제품 기획 단계 완료',date:'완료'}]});

function show(id){['loading','setupScreen','authScreen','app'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
function configured(){return C.supabaseUrl?.startsWith('https://')&&(C.supabasePublishableKey?.startsWith('sb_publishable_')||localStorage.getItem(KEY_STORE)?.startsWith('sb_publishable_'))}
function initClient(){supabase=createClient(C.supabaseUrl,C.supabasePublishableKey?.startsWith('sb_publishable_')?C.supabasePublishableKey:localStorage.getItem(KEY_STORE),{auth:{persistSession:true,detectSessionInUrl:true}})}
async function boot(){if(!configured()){show('setupScreen');return}initClient();const {data:{session}}=await supabase.auth.getSession();if(!session){show('authScreen')}else await enter(session.user);supabase.auth.onAuthStateChange(async(_,session)=>{if(session&&!user)await enter(session.user);if(!session&&user){user=null;show('authScreen')}})}
$('saveSetup').onclick=()=>{const k=$('setupKey').value.trim();if(!k.startsWith('sb_publishable_'))return alert('sb_publishable_로 시작하는 키를 입력해 주세요.');localStorage.setItem(KEY_STORE,k);location.reload()};
$('loginBtn').onclick=async()=>{const email=$('email').value.trim();if(!email)return alert('이메일 주소를 입력해 주세요.');$('loginBtn').disabled=true;$('authMessage').textContent='로그인 링크를 보내는 중입니다…';const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}});$('loginBtn').disabled=false;$('authMessage').textContent=error?'오류: '+error.message:'이메일을 확인하고 로그인 링크를 눌러주세요.'};
$('logoutBtn').onclick=()=>supabase.auth.signOut();

async function enter(u){user=u;$('userEmail').textContent=u.email||'';show('app');await loadProjects();subscribe()}
function normalize(row){const d=row.project_data||{};return{id:row.id,title:row.title||d.title||'새 프로젝트',data:{...emptyData(),...d,type:row.project_type||d.type||'일반 프로젝트',goal:row.goal||d.goal||''}}}
async function loadProjects(){setSync('동기화 중','saving');const {data,error}=await supabase.from('mph_projects').select('*').order('updated_at',{ascending:false});if(error){const cached=JSON.parse(localStorage.getItem(LS_KEY)||'[]');if(cached.length){rows=cached;currentId=rows[0].id;render();setSync('오프라인 저장','error');return}return fail(error)}rows=(data||[]).map(normalize);if(!rows.length)await createProject('My TravelMate AI',seedData());else{currentId=rows[0].id;localStorage.setItem(LS_KEY,JSON.stringify(rows));render();setSync('저장됨')}}
async function createProject(title,data=emptyData()){setSync('저장 중','saving');const result=await supabase.from('mph_projects').insert({owner_id:user.id,title,project_type:data.type||'custom',goal:data.goal||'',project_data:{...data,title}}).select().single();if(result.error)return fail(result.error);const p=normalize(result.data);rows.unshift(p);currentId=p.id;localStorage.setItem(LS_KEY,JSON.stringify(rows));render();setSync('저장됨')}
function current(){return rows.find(x=>x.id===currentId)}
function save(){localStorage.setItem(LS_KEY,JSON.stringify(rows));setSync('저장 중','saving');clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{const p=current();if(!p)return;const {error}=await supabase.from('mph_projects').update({title:p.title,project_type:p.data.type||'custom',goal:p.data.goal||'',project_data:{...p.data,title:p.title}}).eq('id',p.id);error?fail(error):setSync('저장됨')},550)}
function subscribe(){if(channel)supabase.removeChannel(channel);channel=supabase.channel('mph-projects').on('postgres_changes',{event:'UPDATE',schema:'public',table:'mph_projects'},payload=>{if(payload.new.id===currentId){const fresh=normalize(payload.new),i=rows.findIndex(x=>x.id===fresh.id);rows[i]=fresh;render();setSync('동기화됨')}}).subscribe()}
function setSync(text,cls=''){$('syncState').textContent='● '+text;$('syncState').className='sync '+cls}
function fail(e){console.error(e);setSync('저장 오류','error');toast('오류: '+(e.message||e));}
function esc(s=''){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function progress(p){return p.data.phases.length?Math.round(p.data.phases.reduce((a,x)=>a+Number(x.progress||0),0)/p.data.phases.length):0}
function render(){const p=current();if(!p)return;$('projectSelect').innerHTML=rows.map(x=>`<option value="${x.id}" ${x.id===currentId?'selected':''}>${esc(x.title)}</option>`).join('');$('projectTitle').textContent=p.title;$('projectGoal').textContent=p.data.goal||'프로젝트 목표를 입력해 주세요.';$('projectType').textContent=p.data.type||'PROJECT';const pr=progress(p),done=p.data.tasks.filter(x=>x.done).length;$('progressNumber').textContent=pr+'%';$('progressRing').style.setProperty('--p',pr*3.6+'deg');$('progressText').textContent=`${p.data.phases.length}개 단계 · 작업 ${done}/${p.data.tasks.length}개 완료`;$('focusTitle').textContent=p.data.tasks.find(x=>!x.done)?.title||'모든 작업을 완료했습니다';$('stats').innerHTML=[['진행률',pr+'%'],['전체 작업',p.data.tasks.length],['남은 작업',p.data.tasks.length-done],['기록',p.data.logs.length+p.data.ideas.length]].map(x=>`<article class="card stat"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('');renderList(p)}
function renderList(p){$('phaseList').innerHTML=p.data.phases.length?p.data.phases.map(x=>`<div class="item"><div class="progress-row"><strong>${esc(x.name)}</strong><b>${x.progress}%</b><div class="bar"><i style="width:${x.progress}%"></i></div></div><button class="delete" data-del="phases" data-id="${x.id}">×</button></div>`).join(''):empty();$('taskList').innerHTML=p.data.tasks.length?p.data.tasks.map(x=>`<div class="item ${x.done?'done':''}"><input type="checkbox" data-task="${x.id}" ${x.done?'checked':''}><div class="item-content"><h3>${esc(x.title)}</h3><p>${esc(x.detail||'')}</p></div><button class="delete" data-del="tasks" data-id="${x.id}">×</button></div>`).join(''):empty();renderRecords(p,'documents','documentList');renderRecords(p,'roadmap','roadmapList');renderRecords(p,'logs','logList');renderRecords(p,'ideas','ideaList');renderRecords(p,'bugs','bugList');renderRecords(p,'releases','releaseList')}
function renderRecords(p,key,id){$(id).innerHTML=p.data[key].length?p.data[key].map(x=>`<div class="item"><div class="item-content"><h3>${esc(x.title)}</h3><p>${esc(x.detail||'')} ${x.date?'· '+esc(x.date):''}</p></div><button class="delete" data-del="${key}" data-id="${x.id}">×</button></div>`).join(''):empty()}
function empty(){return'<div class="empty">아직 등록된 항목이 없습니다.</div>'}
document.addEventListener('change',e=>{if(e.target.id==='projectSelect'){currentId=e.target.value;render()}if(e.target.dataset.task){const t=current().data.tasks.find(x=>x.id===e.target.dataset.task);t.done=e.target.checked;render();save()}});
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]')?.dataset.view;if(v)switchView(v);const j=e.target.closest('[data-jump]')?.dataset.jump;if(j)switchView(j);const add=e.target.closest('[data-add]')?.dataset.add;if(add)openModal(add);const del=e.target.closest('[data-del]');if(del&&confirm('이 항목을 삭제할까요?')){current().data[del.dataset.del]=current().data[del.dataset.del].filter(x=>x.id!==del.dataset.id);render();save()}});
function switchView(id){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active-view',x.id===id));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
const labels={phases:'단계 추가',tasks:'작업 추가',documents:'문서 추가',roadmap:'로드맵 목표',logs:'개발 일지',ideas:'아이디어',bugs:'버그 등록',releases:'릴리즈 등록'};
function openModal(kind,edit=false){modalKind=kind;editProject=edit;$('modalWrap').classList.remove('hidden');$('modalTitle').textContent=edit?'프로젝트 수정':labels[kind]||'새 프로젝트';if(kind==='project'){const p=edit?current():null;$('modalFields').innerHTML=`<label>프로젝트명<input name="title" required value="${esc(p?.title||'')}"></label><label>종류<input name="type" value="${esc(p?.data.type||'일반 프로젝트')}"></label><label>목표<textarea name="goal">${esc(p?.data.goal||'')}</textarea></label>`}else if(kind==='phases')$('modalFields').innerHTML='<label>단계명<input name="title" required></label><label>진행률<input name="progress" type="number" min="0" max="100" value="0"></label>';else $('modalFields').innerHTML=`<label>제목<input name="title" required></label><label>설명<textarea name="detail"></textarea></label>${kind==='documents'?'<label>상태<select name="status"><option>예정</option><option>진행 중</option><option>완료</option></select></label>':''}`}
function closeModal(){$('modalWrap').classList.add('hidden');$('modalForm').reset()}
$('newProjectBtn').onclick=()=>openModal('project',false);$('editProjectBtn').onclick=()=>openModal('project',true);$('modalClose').onclick=$('modalCancel').onclick=closeModal;
$('modalForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(modalKind==='project'){if(editProject){current().title=f.title;current().data.type=f.type;current().data.goal=f.goal;render();save()}else await createProject(f.title,{...emptyData(),type:f.type,goal:f.goal});closeModal();return}const item={id:crypto.randomUUID(),title:f.title,detail:f.detail||'',date:new Date().toLocaleDateString('ko-KR')};if(modalKind==='phases')current().data.phases.push({id:item.id,name:f.title,progress:Number(f.progress)||0});else if(modalKind==='tasks')current().data.tasks.push({...item,done:false});else current().data[modalKind].unshift({...item,status:f.status});closeModal();render();save()};
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),3500)}
boot();
